name: Manual DB Migration

on:
  workflow_dispatch:

jobs:
  migrate:
    runs-on: ubuntu-latest
    env:
      KUDU_USER: ${{ secrets.AZURE_KUDU_USER }}
      KUDU_PASS: ${{ secrets.AZURE_KUDU_PASS }}
      KUDU_SITE: "https://phronesis-backend-app.scm.azurewebsites.net"

    steps:
      - name: Run Alembic migrations via Kudu API
        run: |
          set -e
          echo "Running Alembic migrations via Kudu API..."
          RESPONSE=$(curl -s -u "$KUDU_USER:$KUDU_PASS" -X POST "$KUDU_SITE/api/command" \
            -H "Content-Type: application/json" \
            -d '{"command": "cd /home/site/wwwroot && poetry run alembic upgrade head"}')
          echo "$RESPONSE"
          # Optionally fail if the response contains an error
          if echo "$RESPONSE" | grep -i error; then
            echo "Migration failed!"
            exit 1
          fi
# Required secrets:
#   - AZURE_KUDU_USER: Kudu deployment username (from Azure Portal > Deployment Center > FTPS credentials)
#   - AZURE_KUDU_PASS: Kudu deployment password
# See WORKFLOWS.md for usage instructions.
